name: test

on:
  pull_request:

jobs:
  test-pep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: sudo apt install tox
      - name: Run tox pep8 env
        run: tox -e pep8
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: sudo apt install tox
      - name: Run tox docs env
        run: tox -e docs
