name: test

on:
  pull_request:

jobs:
  test-pep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tox
        run: sudo apt install -y tox
      - name: Run tox pep8 env
        run: tox run -e pep8
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tox
        run: sudo apt install -y tox
      - name: Run tox docs env
        run: tox run -e docs
