# This workflow helps to test build binero customer documentation

name: Test Build of Binero Customer Docs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Tox
        run: sudo apt install tox

      - name: Build docs
        run: tox -e docs
